services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=postgres_db
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
    ports:
      - 5432:5432

volumes:
  db_data:
    driver: local